rules:
  nesting-depth: 0
  clean-import-paths: 0

  class-name-format:
    - 1
    -
      convention: hyphenatedbem

  property-sort-order:
    - 1
    -
      order: smacss
      ignore-custom-properties: true
