export const FETCH_CEP = 'FETCH_CEP'
export const FETCH_CEP_SUCCESS = 'FETCH_CEP_SUCCESS'
export const FETCH_CEP_FAIL = 'FETCH_CEP_FAIL'

export const FETCH_GEOLOCATION = 'FETCH_GEOLOCATION'
export const FETCH_GEOLOCATION_SUCCESS = 'FETCH_GEOLOCATION_SUCCESS'
export const FETCH_GEOLOCATION_FAIL = 'FETCH_GEOLOCATION_FAIL'
